version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ServerApp/Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    depends_on:
      - server
    networks:
      - app-network
  
  tests:
    build:
      context: .
      dockerfile: Tests/Dockerfile
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - RUN_TESTS=false

networks:
  app-network:
    driver: bridge
