name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build ServerApp with dotnet
      run: dotnet build ServerApp --configuration Release

    - name: Publish ServerApp with dotnet
      run: dotnet publish ServerApp --configuration Release -o ./publish/server

    - name: Build ClientApp with dotnet
      run: dotnet build ClientApp --configuration Release

    - name: Publish ClientApp with dotnet
      run: dotnet publish ClientApp --configuration Release -o ./publish/client

    - name: Build Docker images
      run: |
        docker build -t serverapp:latest -f ServerApp/Dockerfile .
        docker build -t clientapp:latest -f ClientApp/Dockerfile .
